export const variables = {
    success: 'success',
    form: document.querySelector('form'),
    selects: document.querySelectorAll('.select'),
    amountInput: document.getElementById('amount'),
    resultFrom: document.getElementById('resultFrom'),
    resultTo: document.getElementById('resultTo'),
    formResults: document.querySelector('.form-results'),
    rateConversion: document.querySelector(".rate-conversion"),
    rateLast: document.querySelector(".rate-last"),
    switchButton: document.querySelector('.switch-currencies'),
    toSelect: document.getElementById('to'),
    fromSelect: document.getElementById('from'),
    tabs: document.querySelectorAll('.tab'),
    currentCurrency: document.querySelector('.currency-single__item'),
    currentCurrencyList: document.querySelector('.currency-list'),
    singleSelect: document.getElementById('singleSelect'),
    addButton: document.querySelector('.currency-add__button'),
    addCurrencySelect: document.getElementById('addCurrencySelect')
}